### PR TITLE
Update default CNI and helm version

### PR DESCRIPTION
**Pull request by JustinHuang402490**

### CODE REVIEW

**Comment by mJace** [comment]
@EndeavorYen Could you check if you have permission to review this pull request?

**Comment by EndeavorYen** [comment]
Okay. Let me check it. thanks

**Review by EndeavorYen — APPROVED** [review]
It's ok

**Comment by mJace** [comment]
@EndeavorYen @JustinHuang402490 
Here's some note about the git develop policy of x-k8s.
https://hackmd.io/96sP1NbQRkCT5iiKe1ypag?view
You guys can take as a reference and don' have to 100% follow the same principle.

good luck.

**Pull request closed without merging**
